### ISSUE TITLE
Can I send java object by using binder_ndk？

### ISSUE THREAD

**Issue by houzhj58** [lakinduboteju/AndroidNdkBinderExamples#4]
I add function in IMyService.aidl
`void send (Bundle aBundle);`
and `import android.os.Bundle`

but when I exec `gradlew build`, it shows:
`ERROR: android.os.Bundle: couldn't find import for class android.os.Bundle`
I guess beceuse there is no cpp files for java Bundle class.

In google website, there is a funciton [AParcel_fromJavaParcel](https://developer.android.google.cn/ndk/reference/group/ndk-binder#aparcel_fromjavaparcel), but no function AParcle_toJavaParcel.

So if anyone knows how to send java object by using binder_ndk.

**Comment by lakinduboteju** [comment]
@houzhj58,
Sorry for the long delay in replying.

In `IMyService.aidl` there is `String complexType(in ComplexType aComplexObject);` interface method, where `ComplexType` is an Object type.

If you want to see an example of passing an Java Object from a Java client to a C++ binder service, please take a look at following places in the code.
1. Java client : [`JavaBinderClient/src/main/java/.../MainActivity.java` (line 85)](https://github.com/lakinduboteju/AndroidNdkBinderExamples/blob/master/JavaBinderClient/src/main/java/com/example/javabinderclient/MainActivity.java#L85)
2. C++ service : [`NdkBinderService/src/main/cpp/MyService.cpp` (line 15)](https://github.com/lakinduboteju/AndroidNdkBinderExamples/blob/master/NdkBinderService/src/main/cpp/MyService.cpp#L15)

Does this help?
