### ISSUE TITLE
Can a server or client be a  adb executable?

### ISSUE THREAD

**Issue by eudora-jia** [lakinduboteju/AndroidNdkBinderExamples#6]
sorry for reading a little of the code, I just wanna be sure if  a server or client be a  adb executable? I Dont  want java  app layer

**Comment by lakinduboteju** [comment]
Use https://cs.android.com/android to search for the actual code in AOSP.

### Android service that runs outside Android Runtime

#### AIDL

`system/logging/logd/binder/android/os/ILogd.aidl`

``` java
interface ILogd {
    void approve(in int uid, in int gid, in int pid, in int fd);
    void decline(in int uid, in int gid, in int pid, in int fd);
}
```

#### C++ service implementation

`system/logging/logd/LogdNativeService.h`

``` cpp
#include "android/os/BnLogd.h"

class LogdNativeService : public android::os::BnLogd {
  public:
    LogdNativeService(...);

    android::binder::Status approve(int32_t, int32_t, int32_t, int32_t);
    android::binder::Status decline(int32_t, int32_t, int32_t, int32_t);
};
```

`system/logging/logd/LogdNativeService.cpp`

``` cpp
#include "LogdNativeService.h"

LogdNativeService::LogdNativeService(...) {}

android::binder::Status LogdNativeService::approve(int32_t uid, int32_t gid, int32_t pid,
                                                   int32_t fd) {
    // Implementation comes here...
    return android::binder::Status::ok();
}

android::binder::Status LogdNativeService::decline(int32_t uid, int32_t gid, int32_t pid,
                                                   int32_t fd) {
    // Implementation comes here...
    return android::binder::Status::ok();
}
```

#### C++ standalone program that hosts the service

`system/logging/logd/LogReader.cpp`

``` cpp
#include "LogdNativeService.h"

using android::defaultServiceManager;
using android::sp;
using android::String16;

sp<LogdNativeService> service = new LogdNativeService(...);
defaultServiceManager()->addService(String16("logd"), service);
```

#### Build configuration of C++ standalone program

`system/logging/logd/Android.bp`

```
cc_binary {
    name: "logd",
    // logd standalone program is executed at system startup via init.rc
    init_rc: ["logd.rc"],

    srcs: [
        "main.cpp",
        "LogdNativeService.cpp",
        ...
    ],

    shared_libs: [
        "libbinder",
        ...
    ],
}
```

This pure C++ service runs directly on Linux, not on the Android Runtime.
If you have an AOSP build and if you add a pure C++ standalone program like this, you may have to define SELiux policies as well for that.
Like that, you can prepare an service executable with your AOSP build. You may need root adb access to run it on the device.
